---
abstract: 'Wrapper to interact with the Lumeta IPsonar API'
author:
  - 'George Budd <gbudd@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPsonar
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Net::SSLeay: 0
  Test::More: 0
  URI: 0
  XML::Simple: 0
version: ''
